#!/usr/bin/env python3
"""wiki_tool.py — deterministic build, lint, and source tooling for the LLM Wiki.

Standard library only. All commands are run from anywhere; paths resolve
relative to the vault root (the parent of this script's folder).

Commands:
  doctor            non-mutating health check
  build             regenerate Wiki/catalog.jsonl, Wiki/index.md, per-folder indexes
  lint              validate compiled Wiki note frontmatter and source links
  source-scan       list Raw sources; --update writes Schema/source-manifest.jsonl;
                    --accept-covered marks covered sources as processed
  source-lint       validate Raw source frontmatter and coverage state
  source-delta      show Raw sources not represented in the manifest
  source-coverage   show which Raw sources are covered by compiled Wiki notes
  search-catalog    search compiled Wiki notes through the catalog
  log               append a short entry to Wiki/log.md
"""

import argparse
import datetime
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "Wiki"
RAW_SOURCES = ROOT / "Raw" / "Sources"
RAW_FILES = ROOT / "Raw" / "Files"
SCHEMA = ROOT / "Schema"
TEMPLATES = ROOT / "_templates"
CATALOG = WIKI / "catalog.jsonl"
MANIFEST = SCHEMA / "source-manifest.jsonl"
LOG_FILE = WIKI / "log.md"

WIKI_FOLDERS = ["Topics", "Concepts", "Entities", "Projects", "Logs"]
ALLOWED_TAGS = ["topic", "concept", "entity", "project", "log"]
TAG_FOLDERS = {
    "topic": "Topics",
    "concept": "Concepts",
    "entity": "Entities",
    "project": "Projects",
    "log": "Logs",
}
STATUSES = {"seed", "growing", "evergreen"}
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)
KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):(.*)$")
GENERATED_HEADER = "<!-- generated by scripts/wiki_tool.py build; do not edit by hand -->"


# ---------------------------------------------------------------- helpers

def write_text(path, content):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def read_text(path):
    return Path(path).read_text(encoding="utf-8")


def rel(path):
    return Path(path).resolve().relative_to(ROOT).as_posix()


def today():
    return datetime.date.today().isoformat()


def _scalar(raw):
    v = raw.strip()
    if not v:
        return ""
    if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
        return v[1:-1]
    low = v.lower()
    if low == "true":
        return True
    if low == "false":
        return False
    try:
        return int(v)
    except ValueError:
        return v


def parse_frontmatter(text):
    """Minimal YAML frontmatter parser (scalars, block lists, inline lists).

    Returns (dict-or-None, body). None means no frontmatter block found.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None, text
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return None, text
    data = {}
    key = None
    for raw in lines[1:end]:
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        m = KEY_RE.match(stripped) if not raw[:1] in (" ", "\t") else None
        if m:
            key = m.group(1)
            rest = m.group(2).strip()
            if rest == "":
                data[key] = None
            elif rest.startswith("[") and rest.endswith("]"):
                inner = rest[1:-1].strip()
                data[key] = [_scalar(x) for x in inner.split(",")] if inner else []
            else:
                data[key] = _scalar(rest)
        elif stripped == "-" or stripped.startswith("- "):
            if key is None:
                continue
            if data.get(key) is None:
                data[key] = []
            if isinstance(data[key], list):
                data[key].append(_scalar(stripped[1:]))
    return data, "\n".join(lines[end + 1:])


def as_list(value):
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def note_title(body, fallback):
    m = H1_RE.search(body)
    return m.group(1).strip() if m else fallback


def load_note(path):
    return parse_frontmatter(read_text(path))


def compiled_notes():
    notes = []
    for folder in WIKI_FOLDERS:
        d = WIKI / folder
        if not d.is_dir():
            continue
        for p in sorted(d.glob("*.md")):
            if p.name.lower() == "index.md":
                continue
            notes.append(p)
    return notes


def raw_sources():
    if not RAW_SOURCES.is_dir():
        return []
    return sorted(RAW_SOURCES.glob("*.md"))


def coverage_map():
    """Map of Raw source path -> sorted list of compiled note paths citing it."""
    cov = {}
    for p in compiled_notes():
        fm, _ = load_note(p)
        for s in as_list((fm or {}).get("sources")):
            s = str(s).replace("\\", "/")
            cov.setdefault(s, []).append(rel(p))
    return {k: sorted(v) for k, v in cov.items()}


def load_catalog():
    entries = []
    for line in read_text(CATALOG).splitlines():
        if line.strip():
            entries.append(json.loads(line))
    return entries


def load_manifest():
    entries = {}
    if MANIFEST.is_file():
        for line in read_text(MANIFEST).splitlines():
            if line.strip():
                e = json.loads(line)
                entries[e["path"]] = e
    return entries


def note_tag(fm):
    allowed = [t for t in as_list(fm.get("tags")) if t in ALLOWED_TAGS]
    return allowed[0] if allowed else ""


def report(errors, warnings, label):
    for path, msg in warnings:
        print(f"WARN  {path}: {msg}")
    for path, msg in errors:
        print(f"ERROR {path}: {msg}")
    if errors:
        print(f"{label}: FAILED ({len(errors)} error(s), {len(warnings)} warning(s))")
        return 1
    print(f"{label}: OK ({len(warnings)} warning(s))")
    return 0


# ---------------------------------------------------------------- commands

def cmd_doctor(args):
    ok = True
    version = sys.version.split()[0]
    if sys.version_info < (3, 8):
        print(f"ERROR python {version} (need 3.8+)")
        ok = False
    else:
        print(f"ok    python {version}")
    required = [RAW_SOURCES, RAW_FILES, SCHEMA, TEMPLATES, ROOT / "scripts"]
    required += [WIKI / f for f in WIKI_FOLDERS]
    for d in required:
        if d.is_dir():
            print(f"ok    {d.relative_to(ROOT).as_posix()}/")
        else:
            print(f"ERROR missing folder {d.relative_to(ROOT).as_posix()}/")
            ok = False
    print(f"info  raw sources: {len(raw_sources())}")
    print(f"info  compiled wiki notes: {len(compiled_notes())}")
    if CATALOG.is_file():
        try:
            print(f"ok    catalog: {len(load_catalog())} entries")
        except (json.JSONDecodeError, UnicodeDecodeError) as exc:
            print(f"ERROR catalog unreadable: {exc}")
            ok = False
    else:
        print("info  catalog not built yet (run: python scripts/wiki_tool.py build)")
    if MANIFEST.is_file():
        try:
            print(f"ok    source manifest: {len(load_manifest())} entries")
        except (json.JSONDecodeError, UnicodeDecodeError) as exc:
            print(f"ERROR source manifest unreadable: {exc}")
            ok = False
    else:
        print("info  source manifest not built yet "
              "(run: python scripts/wiki_tool.py source-scan --update)")
    print("doctor: OK" if ok else "doctor: FAILED")
    return 0 if ok else 1


def cmd_build(args):
    entries = []
    for p in compiled_notes():
        fm, body = load_note(p)
        fm = fm or {}
        entries.append({
            "path": rel(p),
            "title": note_title(body, p.stem),
            "tag": note_tag(fm),
            "topics": [str(t) for t in as_list(fm.get("topics"))],
            "sources": [str(s).replace("\\", "/") for s in as_list(fm.get("sources"))],
            "updated": str(fm.get("updated") or ""),
        })
    entries.sort(key=lambda e: e["path"])
    write_text(CATALOG, "".join(
        json.dumps(e, ensure_ascii=False, separators=(",", ":")) + "\n" for e in entries))
    print(f"wrote {rel(CATALOG)} ({len(entries)} entries)")

    for folder in WIKI_FOLDERS:
        d = WIKI / folder
        d.mkdir(parents=True, exist_ok=True)
        items = [e for e in entries if e["path"].startswith(f"Wiki/{folder}/")]
        lines = [GENERATED_HEADER, "", f"# {folder} Index", ""]
        if items:
            for e in items:
                fname = e["path"].rsplit("/", 1)[-1]
                updated = e["updated"] or "n/a"
                lines.append(f"- [{e['title']}]({fname}) — updated {updated}")
        else:
            lines.append("_No notes yet._")
        write_text(d / "index.md", "\n".join(lines) + "\n")
        print(f"wrote Wiki/{folder}/index.md ({len(items)} notes)")

    lines = [GENERATED_HEADER, "", "# Wiki Index", "",
             f"{len(entries)} compiled notes. Search first:", "",
             '    python scripts/wiki_tool.py search-catalog --query "text"', ""]
    for folder in WIKI_FOLDERS:
        items = [e for e in entries if e["path"].startswith(f"Wiki/{folder}/")]
        lines.append(f"## {folder} ({len(items)})")
        lines.append("")
        if items:
            for e in items:
                href = e["path"][len("Wiki/"):]
                lines.append(f"- [{e['title']}]({href})")
        else:
            lines.append("_No notes yet._")
        lines.append("")
    if LOG_FILE.is_file():
        lines.append("## Log")
        lines.append("")
        lines.append("- [Wiki change log](log.md)")
        lines.append("")
    write_text(WIKI / "index.md", "\n".join(lines) + "\n")
    print(f"wrote Wiki/index.md ({len(entries)} entries)")
    return 0


def cmd_lint(args):
    errors, warnings = [], []
    for p in sorted(WIKI.glob("*.md")):
        if p.name not in ("index.md", "log.md"):
            errors.append((rel(p), "compiled notes must live in one of: "
                           + ", ".join(f"Wiki/{f}/" for f in WIKI_FOLDERS)))
    for p in compiled_notes():
        r = rel(p)
        fm, body = load_note(p)
        if fm is None:
            errors.append((r, "missing YAML frontmatter"))
            continue
        tags = as_list(fm.get("tags"))
        allowed = [t for t in tags if t in ALLOWED_TAGS]
        if len(allowed) != 1:
            errors.append((r, f"needs exactly one allowed tag ({', '.join(ALLOWED_TAGS)}); "
                           f"found {allowed or tags or 'none'}"))
        else:
            expected = TAG_FOLDERS[allowed[0]]
            if p.parent.name != expected:
                errors.append((r, f"tag '{allowed[0]}' belongs in Wiki/{expected}/, "
                               f"not Wiki/{p.parent.name}/"))
        for field in ("created", "updated"):
            value = str(fm.get(field) or "")
            if not DATE_RE.match(value):
                errors.append((r, f"'{field}' must be YYYY-MM-DD (found: {value or 'missing'})"))
        status = fm.get("status")
        if status is None:
            warnings.append((r, "missing 'status' (seed | growing | evergreen)"))
        elif str(status) not in STATUSES:
            errors.append((r, f"invalid status '{status}' (allowed: seed, growing, evergreen)"))
        sources = [str(s).replace("\\", "/") for s in as_list(fm.get("sources"))]
        for s in sources:
            if not s.startswith("Raw/Sources/"):
                errors.append((r, f"source link must point under Raw/Sources/: {s}"))
            elif not (ROOT / s).is_file():
                errors.append((r, f"source link points to missing file: {s}"))
        count = fm.get("source_count")
        if not isinstance(count, int) or count != len(sources):
            errors.append((r, f"source_count must equal len(sources)={len(sources)} "
                           f"(found: {count!r})"))
        if not sources:
            warnings.append((r, "no sources listed — every compiled note should link "
                             "to at least one Raw source"))
    return report(errors, warnings, "lint")


def _flip_processed(path):
    text = read_text(path)
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return False
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            break
        if re.match(r"^Processed:\s*", lines[i]):
            lines[i] = "Processed: true"
            trailing = "\n" if text.endswith("\n") else ""
            write_text(path, "\n".join(lines) + trailing)
            return True
    return False


def cmd_source_scan(args):
    update = args.update or args.accept_covered
    cov = coverage_map()
    old = load_manifest()
    entries = []
    flipped = []
    for p in raw_sources():
        r = rel(p)
        fm, body = load_note(p)
        fm = fm or {}
        processed = fm.get("Processed") is True
        covered_by = cov.get(r, [])
        if args.accept_covered and covered_by and not processed:
            if _flip_processed(p):
                processed = True
                flipped.append(r)
        entry = {
            "path": r,
            "title": str(fm.get("Title") or "") or note_title(body, p.stem),
            "processed": processed,
            "covered_by": covered_by,
            "updated": today(),
        }
        prev = old.get(r)
        if prev and all(prev.get(k) == entry[k]
                        for k in ("path", "title", "processed", "covered_by")):
            entry["updated"] = prev.get("updated", entry["updated"])
        entries.append(entry)
        print(f"{r} processed={str(processed).lower()} covered_by={len(covered_by)}")
    if flipped:
        print("marked processed: " + ", ".join(flipped))
    if update:
        write_text(MANIFEST, "".join(
            json.dumps(e, ensure_ascii=False, separators=(",", ":")) + "\n" for e in entries))
        print(f"wrote {rel(MANIFEST)} ({len(entries)} entries)")
    else:
        print(f"scanned {len(entries)} source(s) (dry run; use --update to write manifest)")
    return 0


def cmd_source_lint(args):
    errors, warnings = [], []
    cov = coverage_map()
    manifest = load_manifest() if MANIFEST.is_file() else None
    if manifest is None:
        warnings.append(("Schema/source-manifest.jsonl",
                         "missing — run: python scripts/wiki_tool.py source-scan --update"))
    for p in raw_sources():
        r = rel(p)
        fm, _ = load_note(p)
        if fm is None:
            errors.append((r, "missing YAML frontmatter"))
            continue
        for field in ("Title", "Reference", "Created", "Processed", "tags"):
            if field not in fm:
                errors.append((r, f"missing required field '{field}'"))
        if "Title" in fm and not str(fm.get("Title") or "").strip():
            errors.append((r, "'Title' must not be empty"))
        if "Reference" in fm and not str(fm.get("Reference") or "").strip():
            errors.append((r, "'Reference' must not be empty"))
        if "Created" in fm and not DATE_RE.match(str(fm.get("Created") or "")):
            errors.append((r, f"'Created' must be YYYY-MM-DD (found: {fm.get('Created')!r})"))
        if "Processed" in fm and not isinstance(fm.get("Processed"), bool):
            errors.append((r, f"'Processed' must be true or false (found: {fm.get('Processed')!r})"))
        if "tags" in fm and "source" not in as_list(fm.get("tags")):
            errors.append((r, "tags must include 'source'"))
        if fm.get("Processed") is True and not cov.get(r):
            errors.append((r, "marked Processed: true but no compiled Wiki note lists it "
                           "in 'sources'"))
        if manifest is not None:
            m = manifest.get(r)
            if m is None:
                warnings.append((r, "not in manifest — run: python scripts/wiki_tool.py "
                                 "source-scan --update"))
            elif bool(m.get("processed")) != (fm.get("Processed") is True):
                warnings.append((r, "manifest 'processed' out of sync with frontmatter — "
                                 "run: python scripts/wiki_tool.py source-scan --update"))
    if manifest:
        on_disk = {rel(p) for p in raw_sources()}
        for path in sorted(set(manifest) - on_disk):
            warnings.append((path, "in manifest but file is missing — run: "
                             "python scripts/wiki_tool.py source-scan --update"))
    return report(errors, warnings, "source-lint")


def cmd_source_delta(args):
    manifest = load_manifest()
    on_disk = [rel(p) for p in raw_sources()]
    missing = [r for r in on_disk if r not in manifest]
    orphaned = sorted(set(manifest) - set(on_disk))
    for r in missing:
        print(f"not in manifest: {r}")
    for r in orphaned:
        print(f"in manifest but missing on disk: {r}")
    if not missing and not orphaned:
        print("source-delta: manifest matches Raw/Sources/")
    else:
        print(f"source-delta: {len(missing)} unrepresented, {len(orphaned)} orphaned "
              "(run: python scripts/wiki_tool.py source-scan --update)")
    return 0


def cmd_source_coverage(args):
    cov = coverage_map()
    sources = raw_sources()
    covered = 0
    for p in sources:
        r = rel(p)
        notes = cov.get(r, [])
        if notes:
            covered += 1
            print(f"{r} <- {', '.join(notes)}")
        else:
            print(f"{r} UNCOVERED")
    print(f"source-coverage: {covered}/{len(sources)} covered")
    return 0


def cmd_search_catalog(args):
    if not CATALOG.is_file():
        print("catalog missing — run: python scripts/wiki_tool.py build")
        return 1
    tokens = [t for t in args.query.lower().split() if t]
    if not tokens:
        print("empty query")
        return 1
    matches = []
    for e in load_catalog():
        hay = " ".join([e.get("title", ""), e.get("path", ""), e.get("tag", ""),
                        " ".join(e.get("topics", []))]).lower()
        note = ROOT / e.get("path", "")
        body = read_text(note).lower() if note.is_file() else ""
        if all(t in hay or t in body for t in tokens):
            matches.append(e)
    for e in matches:
        print(f"{e['path']} — {e['title']} [{e['tag']}]")
    print(f"search-catalog: {len(matches)} match(es) for {args.query!r}")
    return 0


def cmd_log(args):
    if not LOG_FILE.is_file():
        header = ("# Wiki Log\n\nAppend-only log of meaningful Wiki changes. "
                  "Add entries with:\n\n"
                  '    python scripts/wiki_tool.py log --title "..." --details "..."\n')
    else:
        header = read_text(LOG_FILE)
    entry = f"\n## {today()} — {args.title}\n\n{args.details}\n"
    write_text(LOG_FILE, header + entry)
    print(f"appended log entry to {rel(LOG_FILE)}: {args.title}")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(prog="wiki_tool.py",
                                     description="Deterministic LLM Wiki tooling")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("doctor", help="non-mutating health check").set_defaults(func=cmd_doctor)
    sub.add_parser("build", help="regenerate catalog and indexes").set_defaults(func=cmd_build)
    sub.add_parser("lint", help="validate compiled Wiki notes").set_defaults(func=cmd_lint)

    scan = sub.add_parser("source-scan", help="list Raw sources / update manifest")
    scan.add_argument("--update", action="store_true", help="write Schema/source-manifest.jsonl")
    scan.add_argument("--accept-covered", action="store_true",
                      help="mark covered sources as processed (implies --update)")
    scan.set_defaults(func=cmd_source_scan)

    sub.add_parser("source-lint", help="validate Raw source notes").set_defaults(
        func=cmd_source_lint)
    sub.add_parser("source-delta", help="show sources missing from manifest").set_defaults(
        func=cmd_source_delta)
    sub.add_parser("source-coverage", help="show Wiki coverage of Raw sources").set_defaults(
        func=cmd_source_coverage)

    search = sub.add_parser("search-catalog", help="search compiled notes via catalog")
    search.add_argument("--query", required=True, help="search text")
    search.set_defaults(func=cmd_search_catalog)

    log = sub.add_parser("log", help="append an entry to Wiki/log.md")
    log.add_argument("--title", required=True)
    log.add_argument("--details", required=True)
    log.set_defaults(func=cmd_log)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
